# -*- coding: utf-8 -*-
#
# PyFVCOM2 documentation build configuration file.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import types

sys.path.insert(0, os.path.abspath('../..'))
sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('../../pyfvcom2'))

if 'pyfvcom2.version' not in sys.modules:
    version_module = types.ModuleType('pyfvcom2.version')
    version_module.short_version = '0.0.0'
    version_module.version = '0.0.0'
    version_module.full_version = '0.0.0'
    sys.modules['pyfvcom2.version'] = version_module


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['autodoc2',
              'myst_parser',
              'sphinx.ext.autodoc',
              'sphinx.ext.autosummary',
              'sphinx.ext.napoleon',
              'sphinx.ext.todo',
              'sphinx.ext.mathjax',
              'sphinx.ext.githubpages',
              'sphinx_copybutton',
              'nbsphinx',
              'sphinx_rtd_theme',
              'IPython.sphinxext.ipython_console_highlighting']

# Autodoc2
autodoc2_packages = ['../../pyfvcom2']

# Control autodoc2 output depth and content
autodoc2_output_dir = "../build/apidocs"
autodoc2_index_template = None  # Use default template

# Configure autodoc2 to generate less nested content
autodoc2_module_all_regexes = []

# Control autodoc2 content inclusion
autodoc2_skip_module_regexes = [
    r".*\.tests?.*",  # Skip test modules
    r".*\._.*",      # Skip private modules
]

# Autodoc
napoleon_google_docstring = True
napoleon_use_ivar = True
autodoc_mock_imports = [
    'cartopy',
    'cmocean',
    'pyproj',
    'stripy',
    'utide',
]

# Use this kernel instead of the one stored in the notebook metadata:
nbsphinx_kernel_name = 'python3'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document.
master_doc = 'index'
root_doc = 'index'

# Control HTML table of contents depth
html_theme_options = {
    'navigation_depth': 2,  # Limit sidebar navigation depth
    'collapse_navigation': True,  # Collapse navigation sections
    'sticky_navigation': True,
    'includehidden': False,  # Don't include hidden toctree entries
}

# General information about the project.
project = 'PyFVCOM2'
copyright = '2025, James R. Clark'
author = 'James R. Clark'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# Import version from the package
try:
    from pyfvcom2.version import short_version, version as full_version
    # The short X.Y version.
    version = short_version
    # The full version, including alpha/beta/rc tags.
    release = full_version
except ImportError:
    # Fallback if import fails
    version = '0.0.0'
    release = '0.0.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['**.ipynb_checkpoints', 'apidocs/**']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Google analytics
googleanalytics_id = 'G-5045ZREHMB'

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'PyFVCOM2doc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'PyFVCOM2.tex', 'PyFVCOM2 Documentation',
     'James R. Clark', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'pyfvcom2', 'PyFVCOM2 Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'PyFVCOM2', 'PyFVCOM2 Documentation',
     author, 'PyFVCOM2', 'A Python package for processing FVCOM (Finite Volume Community Ocean Model) data',
     'Miscellaneous'),
]

# Display the committed notebooks without executing them during RTD builds.
nbsphinx_execute = 'never'


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'python': ('https://docs.python.org/3', None)}
